2022-03-10 11:40:52,398 ERROR: Exception on /update_weight/tom [POST] [in c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\oconn\LockerRoom\application\main\routes.py", line 232, in update_weight
    return redirect(url_for('user', username=user.username))
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2022-03-10 20:37:07,316 INFO: LockerRoom startup [in C:\Users\oconn\LockerRoom\application\__init__.py:58]
2022-03-10 20:37:31,348 INFO: tom logged in successfully [in C:\Users\oconn\LockerRoom\application\auth\routes.py:36]
2022-03-10 20:38:22,647 ERROR: Exception on /update_weight/tom [POST] [in c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\oconn\LockerRoom\application\main\routes.py", line 232, in update_weight
    return redirect(url_for('user', username=user.username))
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "c:\users\oconn\lockerroom\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
